name: Deploy to ESP8266 Server

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H 5.188.200.187 >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        rsync -avz --delete \
        -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
        --exclude='.git/' \
        --exclude='.github/' \
        --exclude='node_modules/' \
        --exclude='.env' \
        ./ root@5.188.200.187:/home/esp8266_server/

    - name: Install dependencies and restart PM2
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@5.188.200.187 "
          # Загружаем nvm environment
          export NVM_DIR=\"$HOME/.nvm\"
          [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"

          cd /home/esp8266_server
          echo '📦 Installing dependencies...'
          /root/.nvm/versions/node/v20.10.0/bin/npm install
          echo '🔄 Restarting PM2 process esp_serv...'
          /root/.nvm/versions/node/v20.10.0/bin/pm2 restart esp_serv --update-env
          echo '✅ PM2 process esp_serv restarted successfully'
          /root/.nvm/versions/node/v20.10.0/bin/pm2 save
        "